# Generated by Django 5.2.6 on 2025-09-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(default='http://localhost')),
                ('url_production', models.URLField()),
                ('port', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Microservicio',
                'verbose_name_plural': 'Microservicios',
            },
        ),
    ]
