# Generated by Django 5.2.6 on 2025-09-13 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.IntegerField(help_text='ID de la habitación reservada.')),
                ('user_id', models.IntegerField(help_text='ID del usuario que realiza la reserva.')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Reserva Pendiente'), ('confirmed', 'Reserva Confirmada'), ('preparing', 'Habitación en preparación'), ('maintenance', 'Habitación en mantenimiento'), ('occupied', 'Ocupada'), ('cancelled', 'Reserva Cancelada')], default='pending', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Efectivo'), ('debit_card', 'Tarjeta de Debito'), ('credit_card', 'Tarjeta de Credito'), ('mobile_payment', 'Pago Movil'), ('transfer', 'Transferencia Bancaria')], default='cash', max_length=20)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='reservations.reservation')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
    ]
