# Generated by Django 5.2.7 on 2025-10-08 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='ref_code',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Reserva Pendiente'), ('confirmed', 'Reserva Confirmada'), ('preparing', 'Habitación en preparación'), ('occupied', 'Ocupada'), ('cancelled', 'Reserva Cancelada'), ('completed', 'Reserva Completada')], default='pending', max_length=20),
        ),
    ]
