# Generated by Django 5.2.6 on 2025-09-17 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Individual', 'Single'), ('Matrimonial', 'Double'), ('Cuadruple', 'Squad'), ('Suite', 'Suite')], max_length=100),
        ),
    ]
