# Generated by Django 5.2.7 on 2025-10-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_alter_room_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('Mantenimiento', 'Maintenance'), ('Deshabilitada', 'Disabled'), ('Disponible', 'Available')], default='Disponible', max_length=50),
        ),
    ]
