# Generated by Django 5.2.7 on 2025-10-08 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_room_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('squad', 'Squad'), ('Suite', 'Suite')], max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('maintenance', 'Maintenance'), ('disabled', 'Disabled'), ('available', 'Available')], default='available', max_length=50),
        ),
    ]
